name: your_project_name
description: A new Flutter project.

publish_to: 'none' # Remove this line if you want to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0" # Sesuaikan versi SDK sesuai kebutuhan proyek Anda

dependencies:
  flutter:
    sdk: flutter
  intl: ^0.18.1
  file_picker: ^5.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

assets:
    - assets/jti.png
    - assets/polinema.png